//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiscoKill {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SoapDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SoapDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiscoKill.SoapDictionary", typeof(SoapDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;&lt;soap:Body&gt;&lt;bNecessitaAtualizarListaWebServicesResponse xmlns=&quot;http://tempuri.org/&quot;&gt;&lt;bNecessitaAtualizarListaWebServicesResult&gt;false&lt;/bNecessitaAtualizarListaWebServicesResult&gt;&lt;nErro&gt;0&lt;/nErro&gt;&lt;/bNecessitaAtualizarListaWebServicesResponse&gt;&lt;/soap:Body&gt;&lt;/soap:Envelope&gt;.
        /// </summary>
        internal static string bNecessitaAtualizarListaWebServices {
            get {
                return ResourceManager.GetString("bNecessitaAtualizarListaWebServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;&lt;soap:Body&gt;&lt;bSincronismoAdicionaResponse xmlns=&quot;http://tempuri.org/&quot;&gt;&lt;bSincronismoAdicionaResult&gt;false&lt;/bSincronismoAdicionaResult&gt;&lt;/bSincronismoAdicionaResponse&gt;&lt;/soap:Body&gt;&lt;/soap:Envelope&gt;.
        /// </summary>
        internal static string bSincronismoAdiciona {
            get {
                return ResourceManager.GetString("bSincronismoAdiciona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;&lt;soap:Body&gt;&lt;nCadastraPessoaJuridicaResponse xmlns=&quot;http://tempuri.org/&quot;&gt;&lt;nCadastraPessoaJuridicaResult&gt;110&lt;/nCadastraPessoaJuridicaResult&gt;&lt;/nCadastraPessoaJuridicaResponse&gt;&lt;/soap:Body&gt;&lt;/soap:Envelope&gt;.
        /// </summary>
        internal static string nCadastraPessoaJuridica {
            get {
                return ResourceManager.GetString("nCadastraPessoaJuridica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;&lt;soap:Body&gt;&lt;nRequisicaoDadosVencimentoClienteResponse xmlns=&quot;http://tempuri.org/&quot;&gt;&lt;nRequisicaoDadosVencimentoClienteResult&gt;110&lt;/nRequisicaoDadosVencimentoClienteResult&gt;&lt;dtHoje&gt;2013-09-05T13:52:03.8723750-03:00&lt;/dtHoje&gt;&lt;dtAtualizacao&gt;2013-09-05T13:52:04.1067500-03:00&lt;/dtAtualizacao&gt;&lt;dtVencimento&gt;2110-06-0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nRequisicaoDadosVencimentoCliente {
            get {
                return ResourceManager.GetString("nRequisicaoDadosVencimentoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;&lt;soap:Body&gt;&lt;nRequisicaoDadosVencimentoClienteMaquinaResponse xmlns=&quot;http://tempuri.org/&quot;&gt;&lt;nRequisicaoDadosVencimentoClienteMaquinaResult&gt;1&lt;/nRequisicaoDadosVencimentoClienteMaquinaResult&gt;&lt;dtHoje&gt;2013-09-05T13:52:08.8880000-03:00&lt;/dtHoje&gt;&lt;dtAtualizacao&gt;2013-09-05T13:52:09.1692500-03:00&lt;/dtAtualizacao&gt;&lt;dtV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nRequisicaoDadosVencimentoClienteMaquina {
            get {
                return ResourceManager.GetString("nRequisicaoDadosVencimentoClienteMaquina", resourceCulture);
            }
        }
    }
}
